apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: collector-platform
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: in-cluster
        revision: dev
      - env: staging
        cluster: in-cluster
        revision: staging
      - env: prod
        cluster: in-cluster
        revision: main
  template:
    metadata:
      name: 'collector-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/StanislasTHBD/collector.git
        targetRevision: '{{revision}}'
        path: 'infra/k8s/overlays/{{env}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'collector-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
