apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-appset.yaml
patches:
  - path: patch-repo-server.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
  - path: patch-server.yaml
    target:
      kind: Deployment
      name: argocd-server
  - path: patch-controller.yaml
    target:
      kind: StatefulSet
      name: argocd-application-controller
  - path: patch-redis.yaml
    target:
      kind: Deployment
      name: argocd-redis
