apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/collector/base
  - ingress.yaml

namespace: collectorshop

labels:
  - includeSelectors: true
    pairs:
      env: dev
      app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/stanthbd/collectorshop/web-app
    newTag: sha-be5c72742c261a2b6d6a08d8b779dc83b46b51d9
  - name: ghcr.io/stanthbd/collectorshop/catalog-service
    newTag: sha-be5c72742c261a2b6d6a08d8b779dc83b46b51d9
  - name: ghcr.io/stanthbd/collectorshop/moderation-worker
    newTag: sha-be5c72742c261a2b6d6a08d8b779dc83b46b51d9

