apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
type: Opaque
stringData:
  url: postgresql://collector:password@staging-catalog-db:5432/collector_db?sslmode=disable
  database-url: postgresql://collector:password@staging-catalog-db:5432/collector_db?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: moderation-secrets
type: Opaque
stringData:
  rabbitmq-url: amqp://collector:password@staging-rabbitmq:5672
