apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../apps/collector/base
- ingress.yaml

namespace: collectorshop-prod

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
    env: prod

replicas:
- count: 1
  name: catalog-service
- count: 1
  name: web-app
- count: 1
  name: moderation-worker
- count: 1
  name: keycloak
- count: 1
  name: postgres
- count: 1
  name: rabbitmq
images:
- name: ghcr.io/stanthbd/collectorshop/catalog-service
  newName: ghcr.io/stanthbd/collectorshop/catalog-service
  newTag: sha-a78c67a63a90068531efa063889fe688d9f80ec4
- name: ghcr.io/stanthbd/collectorshop/moderation-worker
  newName: ghcr.io/stanthbd/collectorshop/moderation-worker
  newTag: sha-a78c67a63a90068531efa063889fe688d9f80ec4
- name: ghcr.io/stanthbd/collectorshop/web-app
  newName: ghcr.io/stanthbd/collectorshop/web-app
  newTag: sha-a78c67a63a90068531efa063889fe688d9f80ec4
