apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-db-secret
  namespace: collector-dev
spec:
  encryptedData:
    url: AgAW... # Encrypted value of postgres://collector:password@postgres:5432/collector_db
  template:
    metadata:
      name: catalog-db-secret
      labels:
        managed-by: sealed-secrets
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: collector-dev
spec:
  encryptedData:
    username: AgAW... # Encrypted value of admin
    password: AgAW... # Encrypted value of admin
  template:
    metadata:
      name: keycloak-admin-secret
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: moderation-secrets
  namespace: collector-dev
spec:
  encryptedData:
    rabbitmq-url: AgAW... # Encrypted value of amqp://collector:password@rabbitmq:5672
  template:
    metadata:
      name: moderation-secrets
    type: Opaque
