apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/collector/base
  - ingress.yaml

namespace: collectorshop-staging

labels:
  - includeSelectors: true
    pairs:
      env: staging
      app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/stanthbd/collectorshop/web-app
    newTag: sha-762b2d000541564515c9b46447ce70fb221d5be6
  - name: ghcr.io/stanthbd/collectorshop/catalog-service
    newTag: sha-762b2d000541564515c9b46447ce70fb221d5be6
  - name: ghcr.io/stanthbd/collectorshop/moderation-worker
    newTag: sha-762b2d000541564515c9b46447ce70fb221d5be6

patches:
  - target:
      kind: Ingress
      name: management-ui
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.rabbitmq.local
  - target:
      kind: Ingress
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.keycloak.local

replicas:
  - name: catalog-service
    count: 0
  - name: web-app
    count: 0
  - name: moderation-worker
    count: 0
  - name: keycloak
    count: 0
  - name: postgres
    count: 0
  - name: rabbitmq
    count: 0
