apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-db-secret
spec:
  encryptedData:
    url: AgAW... # Encrypted value for Production
  template:
    metadata:
      name: catalog-db-secret
      labels:
        managed-by: sealed-secrets
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
spec:
  encryptedData:
    username: AgAW...
    password: AgAW...
  template:
    metadata:
      name: keycloak-admin-secret
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: moderation-secrets
spec:
  encryptedData:
    rabbitmq-url: AgAW...
  template:
    metadata:
      name: moderation-secrets
    type: Opaque
